import type { HazardRow, WardRow } from "./types";

export const MOCK_WARDS: WardRow[] = [
  {
    id: "ward_01",
    name: "Nagalagam Street (Kelani River Basin)",
    rainfall_mm: 68,
    river_level_pct: 88,
    status: "CRITICAL",
  },
  {
    id: "ward_02",
    name: "Thimbirigasyaya / Town Hall",
    rainfall_mm: 42,
    river_level_pct: 62,
    status: "WATCH",
  },
  {
    id: "ward_03",
    name: "Pettah / Colombo Fort",
    rainfall_mm: 8,
    river_level_pct: 15,
    status: "NORMAL",
  },
];

export const MOCK_HAZARDS: HazardRow[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    lat: 6.9535,
    lng: 79.8732,
    ward_id: "ward_01",
    category: "FLOOD",
    description: "Waist-deep water near Nagalagam bridge",
    photo_url: null,
    status: "AREA_ALERT",
    urgency: "CRITICAL",
    confidence_score: 0.91,
    is_road_blocked: true,
    confirmations_count: 4,
    created_at: new Date().toISOString(),
    resolved_at: null,
    closure_photo_url: null,
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    lat: 6.9548,
    lng: 79.8734,
    ward_id: "ward_01",
    category: "FLOOD",
    description: "Road impassable, cars stalled",
    photo_url: null,
    status: "PUBLISHED",
    urgency: "CRITICAL",
    confidence_score: 0.84,
    is_road_blocked: true,
    confirmations_count: 2,
    created_at: new Date().toISOString(),
    resolved_at: null,
    closure_photo_url: null,
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    lat: 6.9271,
    lng: 79.8612,
    ward_id: "ward_02",
    category: "FALLEN_TREE",
    description: "Large tree across Bauddhaloka Mawatha",
    photo_url: null,
    status: "COUNCIL_TICKET",
    urgency: "MEDIUM",
    confidence_score: 0.72,
    is_road_blocked: true,
    confirmations_count: 1,
    created_at: new Date().toISOString(),
    resolved_at: null,
    closure_photo_url: null,
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    lat: 6.9355,
    lng: 79.85,
    ward_id: "ward_03",
    category: "HELP_REQUEST",
    description: "Family of 5 needs dry shelter tonight",
    photo_url: null,
    status: "NEED_INFO",
    urgency: "MEDIUM",
    confidence_score: 0.41,
    is_road_blocked: false,
    confirmations_count: 0,
    created_at: new Date().toISOString(),
    resolved_at: null,
    closure_photo_url: null,
  },
];
